### ISSUE TITLE
Icons don't show up below video any more

### ISSUE THREAD

**Issue by Xerus2000** [Pobe16/watch-next#12]
For some time now, the watch next icons haven't appeared below the videos any more, which is really annoying, because I thus can't easily add the current video and play the next :/

**Comment by Pobe16** [comment]
YouTube is now sometimes creating empty <a>'s for new thumbnails that are soon to be created / reused, and as they don't have href attribute, they were causing the script to crash. Added an if to stop the crashing. Just updated the code here, and extension in chrome web store to 1.10.2.  
Please check if it's all right. Sorry for a week of wait time.

**Comment by Xerus2000** [comment]
Seems to work fine now, thank you :+1:
