### ISSUE TITLE
Watch Next breaks if you queue more than fifty videos to watch

### ISSUE THREAD

**Issue by mtearle** [Pobe16/watch-next#2]
I've been travelling so my queue of videos to watch has grown rather large (about 70 items)

The Youtube API call in popup.js Line 55 getDataFromYoutube is restricted to only providing a response for 50 items and errors if you ask for more

I've done a temporary workaround by adding a slice(0,49) to popup.js Line 56  ....

``` javascript
var request = 'https://www.googleapis.com/youtube/v3/videos?id=' + this.videosArray.slice(0,49).join() + '&key='+conFig.youTubeApiKey+
'&fields=items(id,snippet(title,channelTitle,thumbnails(default)),contentDetails(duration),statistics(viewCount))&part=snippet,contentDetails,statistics';
```

Of course, this limits me to only seeing the first 50 videos in the queue.   Probably a more permanent fix/alternative is needed.

**Comment by Pobe16** [comment]
I have got back to coding and I have fixed this. Thanks for submitting the bug!
